### ISSUE TITLE
Game crashes on starting natural magic server

### ISSUE THREAD

**Issue by sethsalieri** [WTFGeeks/Natural-Magic#139]
Game crashed when i try to make a single player world. Crash report included below.

---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 1/7/15 4:07 PM
Description: Starting integrated server

java.lang.ExceptionInInitializerError
    at net.minecraft.server.MinecraftServer.<init>(MinecraftServer.java:146)
    at net.minecraft.server.integrated.IntegratedServer.<init>(IntegratedServer.java:45)
    at net.minecraft.client.Minecraft.func_71371_a(Minecraft.java:2080)
    at net.minecraft.client.gui.GuiCreateWorld.func_146284_a(GuiCreateWorld.java:230)
    at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:225)
    at net.minecraft.client.gui.GuiCreateWorld.func_73864_a(GuiCreateWorld.java:377)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1629)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalStateException: failed to create a child event loop
    at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:61)
    at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:49)
    at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:61)
    at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:52)
    at net.minecraft.network.NetworkSystem.<clinit>(NetworkSystem.java:47)
    ... 18 more
Caused by: io.netty.channel.ChannelException: failed to open a new selector
    at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:128)
    at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:120)
    at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:87)
    at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:57)
    ... 22 more
Caused by: java.io.IOException: Unable to establish loopback connection
    at sun.nio.ch.PipeImpl$Initializer.run(Unknown Source)
    at sun.nio.ch.PipeImpl$Initializer.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.nio.ch.PipeImpl.<init>(Unknown Source)
    at sun.nio.ch.SelectorProviderImpl.openPipe(Unknown Source)
    at java.nio.channels.Pipe.open(Unknown Source)
    at sun.nio.ch.WindowsSelectorImpl.<init>(Unknown Source)
    at sun.nio.ch.WindowsSelectorProvider.openSelector(Unknown Source)
    at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:126)
    ... 25 more
Caused by: java.net.ConnectException: Connection timed out: connect
    at sun.nio.ch.Net.connect0(Native Method)
    at sun.nio.ch.Net.connect(Unknown Source)
    at sun.nio.ch.Net.connect(Unknown Source)
    at sun.nio.ch.SocketChannelImpl.connect(Unknown Source)
    at java.nio.channels.SocketChannel.open(Unknown Source)
    at sun.nio.ch.PipeImpl$Initializer$LoopbackConnector.run(Unknown Source)
    ... 34 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.server.MinecraftServer.<init>(MinecraftServer.java:146)
    at net.minecraft.server.integrated.IntegratedServer.<init>(IntegratedServer.java:45)

-- Starting integrated server --
Details:
    Level ID: New World
    Level Name: New World
Stacktrace:
    at net.minecraft.client.Minecraft.func_71371_a(Minecraft.java:2080)
    at net.minecraft.client.gui.GuiCreateWorld.func_146284_a(GuiCreateWorld.java:230)
    at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:225)
    at net.minecraft.client.gui.GuiCreateWorld.func_73864_a(GuiCreateWorld.java:377)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)

-- Affected screen --
Details:
    Screen name: net.minecraft.client.gui.GuiMainMenu
Stacktrace:
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1629)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 894960096 bytes (853 MB) / 1383522304 bytes (1319 MB) up to 2112618496 bytes (2014 MB)
    JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:-OmitStackTraceInFastThrow -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xms256M -Xmx2048M -XX:MetaspaceSize=128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.85.1272 Minecraft Forge 10.13.2.1272 130 mods loaded, 129 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    FML{7.10.85.1272} [Forge Mod Loader](forge-1.7.10-10.13.2.1272-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Forge{10.13.2.1272} [Minecraft Forge](forge-1.7.10-10.13.2.1272-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CodeChickenCore{1.0.4.29} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    <CoFH ASM>{000} [CoFH ASM Data Initialization](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MobiusCore{1.2.3} [MobiusCore](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NotEnoughItems{1.0.3.74} [Not Enough Items](NotEnoughItems-1.7.10-1.0.3.74-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    OpenEye{0.6} [OpenEye](OpenEye-0.6-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    VeinMiner_coremod{null_build-null} [Core mod](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    OpenModsCore{0.6} [OpenModsCore](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Thaumcraft{4.2.2.1} [Thaumcraft](Thaumcraft-1.7.10-4.2.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    arsmagica2{1.4.0.005} [Ars Magica 2](1.7.10_AM2_1.4.0.005.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    lucky{5.1.0} [Lucky Block]([1-7-10]_Lucky_Block_v5-1-0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    bspkrsCore{6.15} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ArmorStatusHUD{1.28} [ArmorStatusHUD]([1.7.10]ArmorStatusHUD-client-1.28.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CrystalWing{1.7.10.r02} [CrystalWing]([1.7.10]CrystalWing-universal-1.7.10.r02.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    StatusEffectHUD{1.27} [StatusEffectHUD]([1.7.10]StatusEffectHUD-client-1.27.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AppleCore{1.0.1} [AppleCore](AppleCore-mc1.7.10-1.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships](ArchimedesShips-1.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    archmagus{0.6.0} [Archmagus](Archmagus-1.7.10-0.6.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Artifacts{1.1.0} [Artifacts](Artifacts-1.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CoFHCore{1.7.10R3.0.0B9} [CoFH Core](CoFHCore-[1.7.10]3.0.0B9-40.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    asielib{0.3.6} [asielib](AsieLib-1.7.10-0.3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    attainedDrops{1.3} [Attained Drops](AttainedDrops-1.7.10-1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Waila{1.5.7} [Waila](Waila-1.5.7a_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Automagy{0.17.1} [Automagy](Automagy-1.7.10-0.17.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Backpack{2.0.1} [Backpack](backpack-2.0.1-1.7.x.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    iChunUtil{4.1.2} [iChunUtil](iChunUtil-4.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BackTools{4.0.0} [BackTools](BackTools-4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    betterstorage{0.11.3.123} [BetterStorage](BetterStorage-1.7.10-0.11.3.123.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BetterTitleScreen{1.7.10-1.1} [Better Title Screen](BetterTitleScreen-1.7.10-1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BiblioCraft{1.9.1} [BiblioCraft](BiblioCraft[v1.9.1][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    blocklings{2.1.1} [Blocklings](Blocklings-v2.1.1-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AWWayofTime{v1.3.0} [Blood Magic: Alchemical Wizardry](BloodMagic-1.7.10-1.3.0-1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Botania{r1.3-146} [Botania](Botania r1.3-146.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    brewingapi{1.2.0} [Brewing-API](Brewing-API-1.7.2-1.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CarpentersBlocks{3.3.4} [Carpenter's Blocks](Carpenters Blocks v3.3.4 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ChickenChunks{1.3.4.14} [ChickenChunks](ChickenChunks-1.7.10-1.3.4.14-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ForgeMultipart{1.1.1.320} [Forge Multipart](ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    chisel{2.1.3} [Chisel](Chisel 2-2.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    chococraft{4.1.4} [Clienthax's ChocoCraft](ChocoCraft-4.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    colourfulportalsmod{1.4.2} [Colourful Portals](ColourfulPortals-1.4.2_for_1.7.X.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CraftHeraldry{1.1.3} [CraftHeraldry](CraftHeraldry 1.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    DragonMounts{r41-1.7.10} [Dragon Mounts](DragonMounts-r41-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    dungeonpack{1.7.10-1.0} [Dungeon Pack](dungeonpack-1.7.10-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    EnderStorage{1.4.5.25} [EnderStorage](EnderStorage-1.7.10-1.4.5.25-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ExtraUtilities{1.2.1} [Extra Utilities](extrautilities-1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    FastCraft{1.11} [FastCraft](fastcraft-1.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ThaumicTinkerer{unspecified} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-162.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ForbiddenMagic{1.7.10-0.551} [Forbidden Magic](Forbidden Magic-1.7.10-0.551.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Forestry{3.3.0.6} [Forestry for Minecraft](forestry_1.7.10-3.3.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    McMultipart{1.1.1.320} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    fossil{1.7.10 Build 7.0.1} [Fossils and Archeology Revival](Fossils_Archeology_Revival-1.7.10_Build-7.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    foxlib{1.7.10-0.6.0} [FoxLib](FoxLib-1.7.10-0.6.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ganyssurface{1.9.4} [Gany's Surface](Ganys Surface-1.9.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    GardenCore{1.2.0} [Garden Core](GardenStuff-1.7.10-1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    GardenContainers{1.2.1} [Garden Containers](GardenStuff-1.7.10-1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    GardenTrees{1.2.0} [Garden Trees](GardenStuff-1.7.10-1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    GraveStone{2.11.1} [GraveStone](GraveStone 2.11.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Hats{4.0.1} [Hats](Hats-4.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    HatStand{4.0.0} [HatStand](HatStand-4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    HardcoreQuesting{The Journey (4.2.1)} [Hardcore Questing Mode](HQM-The Journey %284.2.1%29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    inpure|core{1.7.10R1.0.0B7} [INpureCore](INpureCore-[1.7.10]1.0.0B7-19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks](InventoryTweaks-1.59-dev-152.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    invinciblehamster{1.4} [invinciblehamster](invinciblehamster-1.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    LunatriusCore{1.1.2.16} [LunatriusCore](LunatriusCore-1.7.10-1.1.2.16-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    lycanitesmobs{1.10.6.1 - MC 1.7.10} [Lycanites Mobs](LycanitesMobsComplete 1.10.6.1 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    arcticmobs{1.10.6.1 - MC 1.7.10} [Lycanites Arctic Mobs](LycanitesMobsComplete 1.10.6.1 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    demonmobs{1.10.6.1 - MC 1.7.10} [Lycanites Demon Mobs](LycanitesMobsComplete 1.10.6.1 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    desertmobs{1.10.6.1 - MC 1.7.10} [Lycanites Desert Mobs](LycanitesMobsComplete 1.10.6.1 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    forestmobs{1.10.6.1 - MC 1.7.10} [Lycanites Forest Mobs](LycanitesMobsComplete 1.10.6.1 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    freshwatermobs{1.10.6.1 - MC 1.7.10} [Lycanites Freshwater Mobs](LycanitesMobsComplete 1.10.6.1 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    infernomobs{1.10.6.1 - MC 1.7.10} [Lycanites Inferno Mobs](LycanitesMobsComplete 1.10.6.1 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    junglemobs{1.10.6.1 - MC 1.7.10} [Lycanites Jungle Mobs](LycanitesMobsComplete 1.10.6.1 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    mountainmobs{1.10.6.1 - MC 1.7.10} [Lycanites Mountain Mobs](LycanitesMobsComplete 1.10.6.1 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    plainsmobs{1.10.6.1 - MC 1.7.10} [Lycanites Plains Mobs](LycanitesMobsComplete 1.10.6.1 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    saltwatermobs{1.10.6.1 - MC 1.7.10} [Lycanites Saltwater Mobs](LycanitesMobsComplete 1.10.6.1 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    shadowmobs{1.10.6.1 - MC 1.7.10} [Lycanites Shadow Mobs](LycanitesMobsComplete 1.10.6.1 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    swampmobs{1.10.6.1 - MC 1.7.10} [Lycanites Swamp Mobs](LycanitesMobsComplete 1.10.6.1 [1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    magicalcrops{1.7.2 - 0.1 ALPHA} [Magical Crops](magicalcrops-1.7.10_0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Mantle{1.7.10-0.3.2.jenkins184} [Mantle](Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    TConstruct{1.7.10-1.8.1.build815} [Tinkers' Construct](TConstruct-1.7.10-1.8.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MagicBees{1.7.10-2.1.22} [Magic Bees](magicbees-1.7.10-2.1.22.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    meteors{2.14} [Falling Meteors](meteors-1.7.10-2.14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    mm{1.7.10-1.1} [Minecraft Money](MinecraftMoney-1.7.10-1.2-01.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineMenu{1.2.0} [MineMenu](MineMenu-1.7.10-1.2.0.B44-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineTweaker3{3.0.9B} [MineTweaker 3](MineTweaker3-1.7.10-3.0.9C.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MobAmputation{4.0.0} [MobAmputation](MobAmputation-4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MobDismemberment{4.0.0} [MobDismemberment](MobDismemberment-4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ModTweaker{0.6} [ModTweaker](ModTweaker-1.7.X-0.6-0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    cfm{3.4.6} [§9MrCrayfish's Furniture Mod](MrCrayfishFurnitureModv3.4.6%281.7.10%29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NEIAddons{1.12.3.11} [NEI Addons](neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NEIAddons|Botany{1.12.3.11} [NEI Addons: Botany](neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NEIAddons|Forestry{1.12.3.11} [NEI Addons: Forestry](neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NEIAddons|CraftingTables{1.12.3.11} [NEI Addons: Crafting Tables](neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NEIAddons|ExNihilo{1.12.3.11} [NEI Addons: Ex Nihilo](neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    neiintegration{1.0.3} [NEI Integration](NEIIntegration-MC1.7.10-1.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    OpenMods{0.6} [OpenMods](OpenModsLib-1.7.10-0.6-snapshot-272.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    OpenBlocks{1.3} [OpenBlocks](OpenBlocks-1.7.10-1.3-snapshot-517.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MapWriter{2.1.1} [MapWriter](Opis-1.2.3_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Opis{1.2.3} [Opis](Opis-1.2.3_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    desertcraft{1.7.2b} [Pam's DesertCraft](Pams DesertCraft 1.7.10a.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    harvestcraft{1.7.10d} [Pam's HarvestCraft](Pams HarvestCraft 1.7.10e.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ProjectE{Alpha 0.2d-dev11} [ProjectE](ProjectE-Alpha 0.2d-dev11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    libsandstone{1.0.0} [libsandstone](LibSandstone-1.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    xreliquary{1.2} [Reliquary](Reliquary-1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Roguelike{1.3.5} [Roguelike Dungeons](roguelike-1.7.10-1.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AS_Ruins{14.4} [Ruins Spawning System](Ruins-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Sanguimancy{1.1.8} [Sanguimancy](Sanguimancy-1.7.10-1.1.8-4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    sinhikabark{1.7.2-0.03} [Sinhika's Bark](SinhikaBark-1.7.2-0.03.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    SlimeCarnage{1.0.4} [Slime Carnage](SlimeCarnage-1.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    soundfilters{0.7_for_1.7.X} [Sound Filters](SoundFilters-0.7_for_1.7.X.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    SSR{rc3} [Soul Shards Reborn](SSR-rc3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    statues{2.1.4} [Statues](statues-1.7.10-2.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    StorageDrawers{1.2.0} [Storage Drawers](StorageDrawers-1.7.10-1.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Tails{1.7.10-1.2.3} [Tails](Tails-1.7.10-1.2.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ThaumicExploration{0.6.0} [Thaumic Exploration](ThaumicExploration-1.7.10-1.1-34.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    erebus{0.2pre11c} [Erebus](TheErebus-0.2pre11c.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    torchLevers{1.4.1} [Torch Levers](TorchLeversV1.4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    TrailMix{4.0.0} [TrailMix](TrailMix-4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    TwilightForest{2.3.2} [The Twilight Forest](twilightforest-1.7.10-2.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    VeinMiner{0.21.1} [Vein Miner](VeinMiner-1.7.10_0.21.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    VeinMinerModSupport{0.21.1} [Mod Support](VeinMiner-1.7.10_0.21.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    VillagersNose{1.3a} [Villager's Nose](VillagersNose-1.7.10-1.3c.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    weaponmod{v1.14.3} [Balkon's WeaponMod](weaponmod-1.14.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    witchery{0.21.0} [Witchery](witchery-1.7.10-0.21.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ForgeMicroblock{1.1.1.320} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    asielibcore{} [AsieLib CoreMod](minecraft.jar) Unloaded->Disabled
    OpenModsLib crash transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:ENABLED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
    Mantle Environment: Environment healthy.
    TConstruct Environment: Environment healthy.
    Stencil buffer state: Function set: GL30, pool: internal, bits: 8
    Launched Version: 1.7.10
    LWJGL: 2.9.1
    OpenGL: Intel(R) HD Graphics 2000 GL version 3.1.0 - Build 9.17.10.3347, Intel
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by sethsalieri** [comment]
Hello?

**Comment by BronyfromOz** [comment]
I think Lewis is on holiday, you may need to wait a bit.  Unless someone else has an answer.

**Comment by sethsalieri** [comment]
Any new news?
