### ISSUE TITLE
Server Error on Startup [0.8]

### ISSUE THREAD

**Issue by eavab** [WTFGeeks/Natural-Magic#176]
I just did a reinstall of our Natural Magic server and I'm getting the following error on startup:

[03:26:12] [main/DEBUG] [FML/]: Discovering coremods
[03:26:12] [main/DEBUG] [FML/]: Examining for coremod candidacy 1.7.10-MB_Battlegear2-Bullseye-1.0.7.0.jar
[03:26:12] [main/TRACE] [FML/]: Found FMLCorePluginContainsFMLMod marker in 1.7.10-MB_Battlegear2-Bullseye-1.0.7.0.jar, it will be examined later for regular @Mod instances
[03:26:12] [main/DEBUG] [FML/]: Instantiating coremod class BattlegearLoadingPlugin
[03:26:12] [main/TRACE] [FML/]: coremod named Mine and Blade: Battlegear2 is loading
[03:26:12] [main/WARN] [FML/]: The coremod mods.battlegear2.coremod.BattlegearLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[03:26:12] [main/DEBUG] [FML/]: Added access transformer class mods.battlegear2.coremod.transformers.BattlegearAccessTransformer to enqueued access transformers
[03:26:12] [main/DEBUG] [FML/]: Enqueued coremod Mine and Blade: Battlegear2
[03:26:12] [main/DEBUG] [FML/]: Examining for coremod candidacy 1.7.10_AM2-1.4.0.008.jar
[03:26:12] [main/TRACE] [FML/]: Found FMLCorePluginContainsFMLMod marker in 1.7.10_AM2-1.4.0.008.jar, it will be examined later for regular @Mod instances
[03:26:12] [main/DEBUG] [FML/]: Instantiating coremod class AM2PreloaderContainer
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NoClassDefFoundError: cpw/mods/fml/common/DummyModContainer
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.ClassLoader.defineClass1(Native Method)
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.security.AccessController.doPrivileged(Native Method)
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.Class.forName0(Native Method)
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.Class.forName(Class.java:270)
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:417)
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:346)
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:214)
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at cpw.mods.fml.relauncher.FMLLaunchHandler.setupServer(FMLLaunchHandler.java:74)
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForServerLaunch(FMLLaunchHandler.java:39)
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at cpw.mods.fml.common.launcher.FMLServerTweaker.injectIntoClassLoader(FMLServerTweaker.java:23)
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.reflect.Method.invoke(Method.java:606)
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.ClassNotFoundException: cpw.mods.fml.common.DummyModContainer
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     ... 29 more
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.NoClassDefFoundError: LZMA/LzmaInputStream
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at cpw.mods.fml.common.asm.transformers.PatchingTransformer.transform(PatchingTransformer.java:10)
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     ... 31 more
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.ClassNotFoundException: LZMA.LzmaInputStream
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.security.AccessController.doPrivileged(Native Method)
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106)
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
[03:26:12] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     ... 34 more
[03:26:12] [main/ERROR] [FML/]: An error occurred trying to configure the minecraft home at /home/minecraft/multicraft/servers/server7783/. for Forge Mod Loader
java.lang.NoClassDefFoundError: cpw/mods/fml/common/DummyModContainer
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_60]
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800) ~[?:1.7.0_60]
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_60]
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[?:1.7.0_60]
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[?:1.7.0_60]
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.7.0_60]
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_60]
    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_60]
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_60]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.11.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_60]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_60]
    at java.lang.Class.forName0(Native Method) ~[?:1.7.0_60]
    at java.lang.Class.forName(Class.java:270) ~[?:1.7.0_60]
    at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:417) ~[forge1.7.10.jar:?]
    at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:346) ~[forge1.7.10.jar:?]
    at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:214) ~[forge1.7.10.jar:?]
    at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [forge1.7.10.jar:?]
    at cpw.mods.fml.relauncher.FMLLaunchHandler.setupServer(FMLLaunchHandler.java:74) [forge1.7.10.jar:?]
    at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForServerLaunch(FMLLaunchHandler.java:39) [forge1.7.10.jar:?]
    at cpw.mods.fml.common.launcher.FMLServerTweaker.injectIntoClassLoader(FMLServerTweaker.java:23) [forge1.7.10.jar:?]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.11.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_60]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_60]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_60]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_60]
    at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43) [forge1.7.10.jar:?]
    at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12) [forge1.7.10.jar:?]
Caused by: java.lang.ClassNotFoundException: cpw.mods.fml.common.DummyModContainer
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_60]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_60]
    ... 29 more
Caused by: java.lang.NoClassDefFoundError: LZMA/LzmaInputStream
    at cpw.mods.fml.common.asm.transformers.PatchingTransformer.transform(PatchingTransformer.java:10) ~[forge1.7.10.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.11.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.11.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_60]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_60]
    ... 29 more
Caused by: java.lang.ClassNotFoundException: LZMA.LzmaInputStream
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[?:1.7.0_60]
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_60]
    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_60]
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_60]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_60]
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) ~[?:1.7.0_60]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_60]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.11.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_60]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_60]
    at cpw.mods.fml.common.asm.transformers.PatchingTransformer.transform(PatchingTransformer.java:10) ~[forge1.7.10.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.11.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.11.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_60]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_60]
    ... 29 more

**Comment by eavab** [comment]
I reinstalled from the ATLauncher directly instead of from the mod pack changelog page and it worked.
