### ISSUE TITLE
client crashes when joining server

### ISSUE THREAD

**Issue by patenged** [WTFGeeks/Natural-Magic#191]
i played on a server for a few days and then suddenly it would crash the game whenever i tried to join.  
here's the crash report

---- Minecraft Crash Report ----
// There are four lights!

Time: 3/26/15 5:26 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
    at com.github.abrarsyed.secretroomsmod.common.OwnershipManager.getOwner(OwnershipManager.java:125)
    at com.github.abrarsyed.secretroomsmod.common.OwnershipManager.isOwner(OwnershipManager.java:115)
    at com.github.abrarsyed.secretroomsmod.blocks.BlockCamoTrapDoor.getPickBlock(BlockCamoTrapDoor.java:429)
    at com.github.abrarsyed.secretroomsmod.client.waila.WailaProvider.getWailaStack(WailaProvider.java:60)
    at mcp.mobius.waila.overlay.RayTracing.getIdentifierItems(RayTracing.java:156)
    at mcp.mobius.waila.overlay.RayTracing.getIdentifierStack(RayTracing.java:97)
    at mcp.mobius.waila.overlay.RayTracing.getTargetStack(RayTracing.java:66)
    at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:76)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_526_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:330)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2052)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at com.github.abrarsyed.secretroomsmod.common.OwnershipManager.getOwner(OwnershipManager.java:125)
    at com.github.abrarsyed.secretroomsmod.common.OwnershipManager.isOwner(OwnershipManager.java:115)
    at com.github.abrarsyed.secretroomsmod.blocks.BlockCamoTrapDoor.getPickBlock(BlockCamoTrapDoor.java:429)
    at com.github.abrarsyed.secretroomsmod.client.waila.WailaProvider.getWailaStack(WailaProvider.java:60)
    at mcp.mobius.waila.overlay.RayTracing.getIdentifierItems(RayTracing.java:156)
    at mcp.mobius.waila.overlay.RayTracing.getIdentifierStack(RayTracing.java:97)
    at mcp.mobius.waila.overlay.RayTracing.getTargetStack(RayTracing.java:66)
    at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:76)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_526_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:330)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['gnall1'/2063484, l='MpServer', x=1124.43, y=64.44, z=-1153.47]]
    Chunk stats: MultiplayerChunkCache: 119, 119
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (1120,113,-1157), Chunk: (at 0,7,11 in 70,-73; contains blocks 1120,0,-1168 to 1135,255,-1153), Region: (2,-3; contains chunks 64,-96 to 95,-65, blocks 1024,0,-1536 to 1535,255,-1025)
    Level time: 17902989 game time, 17873547 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 49 total; [EntityTFNagaSegment['unknown'/128, l='MpServer', x=0.00, y=0.00, z=0.00], EntityTFNagaSegment['unknown'/129, l='MpServer', x=0.00, y=0.00, z=0.00], EntityTFNagaSegment['unknown'/130, l='MpServer', x=0.00, y=0.00, z=0.00], EntityTFNagaSegment['unknown'/131, l='MpServer', x=0.00, y=0.00, z=0.00], EntityGib['unknown'/515, l='MpServer', x=0.00, y=0.00, z=0.00], EntityTFNagaSegment['unknown'/132, l='MpServer', x=0.00, y=0.00, z=0.00], EntityGib['unknown'/516, l='MpServer', x=0.00, y=0.00, z=0.00], EntityTFNagaSegment['unknown'/133, l='MpServer', x=0.00, y=0.00, z=0.00], EntityGib['unknown'/517, l='MpServer', x=0.00, y=0.00, z=0.00], EntityTFNagaSegment['unknown'/134, l='MpServer', x=0.00, y=0.00, z=0.00], EntityTFNagaSegment['unknown'/135, l='MpServer', x=0.00, y=0.00, z=0.00], EntityTFNagaSegment['unknown'/136, l='MpServer', x=0.00, y=0.00, z=0.00], EntityGib['unknown'/520, l='MpServer', x=0.00, y=0.00, z=0.00], EntityTFNagaSegment['unknown'/137, l='MpServer', x=0.00, y=0.00, z=0.00], EntityGib['unknown'/521, l='MpServer', x=0.00, y=0.00, z=0.00], EntityTFNagaSegment['unknown'/138, l='MpServer', x=0.00, y=0.00, z=0.00], EntityGib['unknown'/522, l='MpServer', x=0.00, y=0.00, z=0.00], EntityGib['unknown'/525, l='MpServer', x=0.00, y=0.00, z=0.00], EntityGib['unknown'/526, l='MpServer', x=0.00, y=0.00, z=0.00], EntityGib['unknown'/527, l='MpServer', x=0.00, y=0.00, z=0.00], EntityCreeper['Creeper'/2064400, l='MpServer', x=1132.50, y=14.00, z=-1110.50], EntityClientPlayerMP['gnall1'/2063484, l='MpServer', x=1124.43, y=64.44, z=-1153.47], EntityCreeper['Creeper'/2064399, l='MpServer', x=1131.97, y=14.00, z=-1112.28], EntityGib['unknown'/530, l='MpServer', x=0.00, y=0.00, z=0.00], EntityGib['unknown'/531, l='MpServer', x=0.00, y=0.00, z=0.00], EntityZombie['Zombie'/2064396, l='MpServer', x=1082.38, y=19.00, z=-1136.06], EntityGib['unknown'/532, l='MpServer', x=0.00, y=0.00, z=0.00], EntityGib['unknown'/534, l='MpServer', x=0.00, y=0.00, z=0.00], EntityCreeper['Creeper'/2064392, l='MpServer', x=1085.31, y=45.00, z=-1117.53], EntityGib['unknown'/535, l='MpServer', x=0.00, y=0.00, z=0.00], EntityGib['unknown'/536, l='MpServer', x=0.00, y=0.00, z=0.00], EntityGib['unknown'/540, l='MpServer', x=0.00, y=0.00, z=0.00], EntityGib['unknown'/541, l='MpServer', x=0.00, y=0.00, z=0.00], EntityGib['unknown'/542, l='MpServer', x=0.00, y=0.00, z=0.00], EntityGib['unknown'/545, l='MpServer', x=0.00, y=0.00, z=0.00], EntityGib['unknown'/546, l='MpServer', x=0.00, y=0.00, z=0.00], EntityGib['unknown'/547, l='MpServer', x=0.00, y=0.00, z=0.00], EntitySkeleton['Skeleton'/2064311, l='MpServer', x=1138.09, y=50.00, z=-1167.53], EntitySkeleton['Skeleton'/2064478, l='MpServer', x=1061.50, y=54.00, z=-1128.91], EntityBat['Bat'/2064475, l='MpServer', x=1096.97, y=56.19, z=-1103.44], EntityZombie['Zombie'/2064472, l='MpServer', x=1129.50, y=12.00, z=-1101.06], EntitySpider['Spider'/2064334, l='MpServer', x=1091.72, y=48.00, z=-1116.28], EntitySkeleton['Skeleton'/2064333, l='MpServer', x=1099.50, y=53.00, z=-1111.50], EntityCreeper['Creeper'/2064332, l='MpServer', x=1102.31, y=12.00, z=-1112.00], EntityZombie['Zombie'/2064363, l='MpServer', x=1097.53, y=72.00, z=-1121.16], EntityBrainyZombie['Angry Zombie'/2064360, l='MpServer', x=-6993.50, y=91.00, z=192.50], EntityBat['Bat'/2064482, l='MpServer', x=1084.69, y=24.28, z=-1103.69], EntityBat['Bat'/2064481, l='MpServer', x=1080.28, y=17.00, z=-1103.72], EntityTFNagaSegment['unknown'/127, l='MpServer', x=0.00, y=0.00, z=0.00]]
    Retry entities: 0 total; []
    Server brand: cauldron,craftbukkit,mcpc,fml,forge
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:916)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_40, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 599669952 bytes (571 MB) / 1165029376 bytes (1111 MB) up to 2649489408 bytes (2526 MB)
    JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:-OmitStackTraceInFastThrow -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xms256M -Xmx2560M -XX:MetaspaceSize=256M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 111 mods loaded, 111 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    FML{7.10.85.1291} [Forge Mod Loader](forge-1.7.10-10.13.2.1291-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Forge{10.13.2.1291} [Minecraft Forge](forge-1.7.10-10.13.2.1291-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AM2-Preloader{0.0.2} [AMCore](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CodeChickenCore{1.0.4.35} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    <CoFH ASM>{000} [CoFH ASM Data Initialization](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MobiusCore{1.2.3} [MobiusCore](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NotEnoughItems{1.0.4.90} [Not Enough Items](NotEnoughItems-1.7.10-1.0.4.90-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    OpenEye{0.6} [OpenEye](OpenEye-0.6-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    VeinMiner_coremod{0.26.0_build.unknown} [Core mod](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    battlegear2{1.0.7.0} [Mine & Blade Battlegear 2 - Bullseye](1.7.10-MB_Battlegear2-Bullseye-1.0.7.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AnimationAPI{1.2.4} [AnimationAPI](AnimationAPI-1.7.10-1.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    arsmagica2{1.4.0.008} [Ars Magica 2](1.7.10_AM2-1.4.0.008.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    bspkrsCore{6.15} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ArmorStatusHUD{1.28} [ArmorStatusHUD]([1.7.10]ArmorStatusHUD-client-1.28.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    StatusEffectHUD{1.27} [StatusEffectHUD]([1.7.10]StatusEffectHUD-client-1.27.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AppleCore{1.1.0} [AppleCore](AppleCore-mc1.7.10-1.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Artifacts{1.1.1} [Artifacts](Artifacts-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CoFHCore{1.7.10R3.0.0RC3} [CoFH Core](CoFHCore-[1.7.10]3.0.0RC3-203.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    asielib{0.3.8} [asielib](AsieLib-1.7.10-0.3.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    atum{0.6} [Atum](Atum-1.7.10-0.6.34.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Thaumcraft{4.2.3.5} [Thaumcraft](Thaumcraft-1.7.10-4.2.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Waila{1.5.8} [Waila](Waila-1.5.9_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Automagy{0.20.2} [Automagy](Automagy-1.7.10-0.20.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Backpack{2.0.1} [Backpack](backpack-2.0.1-1.7.x.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    iChunUtil{4.1.3} [iChunUtil](iChunUtil-4.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BackTools{4.0.0} [BackTools](BackTools-4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BattleTowers{1.5.1} [Battle Towers](BattleTowers-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    betterstorage{0.12.0.124} [BetterStorage](BetterStorage-1.7.10-0.12.0.124.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BetterTitleScreen{1.7.10-1.1} [Better Title Screen](BetterTitleScreen-1.7.10-1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BiblioCraft{1.9.2} [BiblioCraft](BiblioCraft[v1.9.2][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AWWayofTime{v1.3.1} [Blood Magic: Alchemical Wizardry](BloodMagic-1.7.10-1.3.1-5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Botania{r1.5-168} [Botania](Botania r1.5-168.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CarpentersBlocks{3.3.5} [Carpenter's Blocks](Carpenters Blocks v3.3.5 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ChickenChunks{1.3.4.17} [ChickenChunks](ChickenChunks-1.7.10-1.3.4.17-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ForgeMultipart{1.1.1.323} [Forge Multipart](ForgeMultipart-1.7.10-1.1.1.323-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    TwilightForest{2.3.4} [The Twilight Forest](twilightforest-1.7.10-2.3.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    chisel{2.3.7.34} [Chisel 2](Chisel2-2.3.7.34.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    chococraft{4.1.5} [Clienthax's ChocoCraft](ChocoCraft-4.1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    chocolateQuest{1.0} [Chocolate Quest](chocolateQuest-1.7.10-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    colourfulportalsmod{1.4.2} [Colourful Portals](ColourfulPortals-1.4.2_for_1.7.X.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CosmeticArmor{1.0.5} [Cosmetic Armor](CosmeticArmor-1.7.10-1.0.5.B8-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CraftHeraldry{1.1.3} [CraftHeraldry](CraftHeraldry 1.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    DragonMounts{r41-1.7.10} [Dragon Mounts](DragonMounts-r41-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    dungeonpack{1.7.10-1.0} [Dungeon Pack](dungeonpack-1.7.10-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    EnderStorage{1.4.5.27} [EnderStorage](EnderStorage-1.7.10-1.4.5.27-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ExtrabiomesXL{3.16.0} [ExtrabiomesXL](extrabiomesxl_1.7.10-3.16.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    FastCraft{1.19} [FastCraft](fastcraft-1.19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ThaumicTinkerer{unspecified} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-463.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ForbiddenMagic{1.7.10-0.561} [Forbidden Magic](Forbidden Magic-1.7.10-0.561.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Forestry{3.4.0.7} [Forestry for Minecraft](forestry_1.7.10-3.4.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    McMultipart{1.1.1.323} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.1.323-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    foss

**Comment by Time6628** [comment]
Try disabling Wailia.

**Comment by patenged** [comment]
it worked!!! thanks:)
