### ISSUE TITLE
Placing Accio Sword alone in a crafting table = crash

### ISSUE THREAD

**Issue by JustJinxed** [WTFGeeks/Natural-Magic#222]
When placing a Accio Sword into a crafting table, by itself, I'm getting a crash. No crash if I put the essence in first (to upgrade it). 

Not sure if this has something to do with Botania's Repair Ivy, or what mod interaction is causing it? 

Full Log: http://pastebin.com/riqNZtYR

cut-
java.lang.ArrayIndexOutOfBoundsException: 42
        at net.minecraft.item.Item$ToolMaterial.func_150995_f(Item.java:1390)
        at net.minecraft.item.Item$ToolMaterial.getRepairItemStack(Item.java:1413)
        at net.minecraft.item.ItemSword.func_82789_a(ItemSword.java:104)
        at vazkii.botania.common.crafting.recipe.RegenIvyRecipe.func_77569_a(RegenIvyRecipe.java:46)
        at net.minecraft.item.crafting.CraftingManager.func_82787_a(CraftingManager.java:323)
        at net.minecraft.inventory.ContainerWorkbench.func_75130_a(SourceFile:53)
        at net.minecraft.inventory.InventoryCrafting.func_70299_a(SourceFile:81)
        at net.minecraft.inventory.Slot.func_75215_d(Slot.java:77)
        at net.minecraft.inventory.Container.func_75144_a(SourceFile:222)
        at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:419)
        at codechicken.nei.guihook.GuiContainerManager.handleSlotClick(GuiContainerManager.java:504)
        at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:638)
        at net.minecraft.client.gui.inventory.GuiContainer.public_func_146984_a(GuiContainer.java)
        at codechicken.nei.guihook.DefaultSlotClickHandler.callHandleMouseClick(DefaultSlotClickHandler.java)
        at codechicken.nei.guihook.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:17)
        at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:453)
        at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
        at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:607)
        at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
        at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
        at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
        at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1628)
        at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
        at net.minecraft.client.main.Main.main(SourceFile:148)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by JustJinxed** [comment]
oh p.s. Somehow I doubt it's them, but I updated MagicalCrops to Beta 4 when I found this, just to be safe. Still happens.
