### ISSUE TITLE
Thaumcraft golems crash server

### ISSUE THREAD

**Issue by frodo12311** [WTFGeeks/Natural-Magic#246]
I am running ATluanchers natural magic modpack version 0.8.1 with applied energistics and thaumic energistics added to it. Both in singleplayer and on the server I run whenever you place a thaumcraft golem it crashes.

Here is the server error log for the crash, I would appreciate any help and some understanding on my incompetence, first server I have ever got running and I am new to the forums.

[23:05:06] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: java.util.HashMap.getOrDefault(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
at thaumicenergistics.common.integration.tc.GolemHooks.hook_SetupGolem(GolemHooks.java:621) ~[GolemHooks.class:?]
at thaumcraft.common.entities.golems.EntityGolemBase.setupGolem(EntityGolemBase.java:288) ~[EntityGolemBase.class:?]
at thaumcraft.common.entities.golems.EntityGolemBase.setup(EntityGolemBase.java:323) ~[EntityGolemBase.class:?]
at thaumcraft.common.entities.golems.ItemGolemPlacer.spawnCreature(ItemGolemPlacer.java:233) ~[ItemGolemPlacer.class:?]
at thaumcraft.common.entities.golems.ItemGolemPlacer.onItemUseFirst(ItemGolemPlacer.java:167) ~[ItemGolemPlacer.class:?]
at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:360) ~[mx.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556) ~[nh.class:?]
at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) ~[nc.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) ~[MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[23:05:06] [Server thread/ERROR]: This crash report has been saved to: C:\Users\Rouge\Desktop\Natural_Server.\crash-reports\crash-2016-02-05_23.05.06-server.txt
[23:05:06] [Server thread/INFO]: Stopping server
[23:05:06] [Server thread/INFO]: Saving players
[23:05:06] [Server thread/INFO]: Saving worlds
[23:05:06] [Server thread/INFO]: Saving chunks for level 'world1'/Overworld
[23:05:07] [Server thread/INFO]: Saving chunks for level 'world1'/Nether
[23:05:07] [Server thread/INFO]: Saving chunks for level 'world1'/Erebus
[23:05:07] [Server thread/INFO]: Saving chunks for level 'world1'/Soul Network Dimension
[23:05:07] [Server thread/INFO]: Saving chunks for level 'world1'/Dungeon
[23:05:07] [Server thread/INFO]: Saving chunks for level 'world1'/Atum
[23:05:07] [Server thread/INFO]: Saving chunks for level 'world1'/SpectreWorld

**Comment by frodo12311** [comment]
I solved it, for those who find this, the problem was Thaumic Energistics 1.0.0.1. It does not work in this mod pack but the older 0.8.10.10 works just fine along with the latetest stable build of Applied energistics.
